name: CI/CD - Frontend App

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Test
        run: |
          npm install
          npm run test

      - name: Build
        run: npm run build

      - name: Docker login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t smartpad/money-minder:front .
          docker push smartpad/money-minder:front
